// ── Bad Moon Rising ────────────────────────────────────────────────
const tb = require('./troubleBrewing');

const roles = {
  // Townsfolk
  GRANDMOTHER: { id: 'GRANDMOTHER', name: 'Abuela', alignment: 'good', type: 'townfolk',
    ability: 'Primera noche: sabes 1 jugador bueno y su personaje. Si el Demonio lo mata, tú también mueres.', firstNight: true, otherNights: false },
  SAILOR: { id: 'SAILOR', name: 'Marinero', alignment: 'good', type: 'townfolk',
    ability: 'Cada noche: elige un jugador vivo. Tú o él estáis borrachos hasta el atardecer. No puedes morir.', firstNight: true, otherNights: true },
  CHAMBERMAID: { id: 'CHAMBERMAID', name: 'Sirvienta', alignment: 'good', type: 'townfolk',
    ability: 'Cada noche: elige 2 jugadores vivos (no a ti). Sabes cuántos despertaron esta noche por su habilidad.', firstNight: true, otherNights: true },
  EXORCIST: { id: 'EXORCIST', name: 'Exorcista', alignment: 'good', type: 'townfolk',
    ability: 'Cada noche*: elige un jugador (distinto al de anoche). Si es el Demonio, sabe quién eres y no despierta esta noche.', firstNight: false, otherNights: true },
  INNKEEPER: { id: 'INNKEEPER', name: 'Posadero', alignment: 'good', type: 'townfolk',
    ability: 'Cada noche*: elige 2 jugadores. No pueden morir esta noche, pero 1 está borracho hasta el atardecer.', firstNight: false, otherNights: true },
  GAMBLER: { id: 'GAMBLER', name: 'Tahúr', alignment: 'good', type: 'townfolk',
    ability: 'Cada noche*: elige un jugador y adivina su personaje. Si fallas, mueres.', firstNight: false, otherNights: true },
  GOSSIP: { id: 'GOSSIP', name: 'Cotilla', alignment: 'good', type: 'townfolk',
    ability: 'Cada día: haz una declaración pública. Esa noche, si es cierta, un jugador muere.', firstNight: false, otherNights: true },
  COURTIER: { id: 'COURTIER', name: 'Cortesano', alignment: 'good', type: 'townfolk',
    ability: 'Una vez por partida, de noche: elige un personaje. Está borracho 3 días y 3 noches.', firstNight: true, otherNights: true },
  PROFESSOR: { id: 'PROFESSOR', name: 'Profesor', alignment: 'good', type: 'townfolk',
    ability: 'Una vez por partida, de noche*: elige un jugador muerto. Si es Aldeano, revive.', firstNight: false, otherNights: true },
  MINSTREL: { id: 'MINSTREL', name: 'Juglar', alignment: 'good', type: 'townfolk',
    ability: 'Cuando un Esbirro muere ejecutado, todos los demás (salvo Viajeros) están borrachos hasta el próximo atardecer.', firstNight: false, otherNights: false },
  TEA_LADY: { id: 'TEA_LADY', name: 'Dama del Té', alignment: 'good', type: 'townfolk',
    ability: 'Si tus dos vecinos vivos son buenos, no pueden morir.', firstNight: false, otherNights: false },
  PACIFIST: { id: 'PACIFIST', name: 'Pacifista', alignment: 'good', type: 'townfolk',
    ability: 'Los jugadores buenos ejecutados pueden no morir.', firstNight: false, otherNights: false },
  FOOL: { id: 'FOOL', name: 'Bufón', alignment: 'good', type: 'townfolk',
    ability: 'La primera vez que mueras, no mueres.', firstNight: false, otherNights: false },
  // Outsiders
  GOON: { id: 'GOON', name: 'Matón', alignment: 'good', type: 'outsider',
    ability: 'Cada noche, el primer jugador que te elija con su habilidad se emborracha hasta el atardecer. Tú adoptas su alineación.', firstNight: false, otherNights: false },
  LUNATIC: { id: 'LUNATIC', name: 'Lunático', alignment: 'good', type: 'outsider',
    ability: 'Crees ser el Demonio pero no lo eres. El Demonio sabe quién eres y a quién eliges de noche.', firstNight: true, otherNights: true },
  TINKER: { id: 'TINKER', name: 'Manitas', alignment: 'good', type: 'outsider',
    ability: 'Puedes morir en cualquier momento.', firstNight: false, otherNights: false },
  MOONCHILD: { id: 'MOONCHILD', name: 'Hijo de la Luna', alignment: 'good', type: 'outsider',
    ability: 'Cuando sepas que has muerto, elige públicamente 1 jugador vivo: si es bueno, muere esa noche.', firstNight: false, otherNights: false },
  // Minions
  GODFATHER: { id: 'GODFATHER', name: 'Padrino', alignment: 'evil', type: 'minion',
    ability: 'Primera noche: sabes qué Forasteros hay. Si un Forastero muere de día, esa noche elige un jugador: muere. [-1 o +1 Forastero]', firstNight: true, otherNights: true },
  DEVILS_ADVOCATE: { id: 'DEVILS_ADVOCATE', name: 'Abogado del Diablo', alignment: 'evil', type: 'minion',
    ability: 'Cada noche: elige un jugador vivo (distinto al de anoche). Si es ejecutado mañana, no muere.', firstNight: true, otherNights: true },
  ASSASSIN: { id: 'ASSASSIN', name: 'Asesino', alignment: 'evil', type: 'minion',
    ability: 'Una vez por partida, de noche*: elige un jugador: muere, aunque por algo no debería poder morir.', firstNight: false, otherNights: true },
  MASTERMIND: { id: 'MASTERMIND', name: 'Mente Maestra', alignment: 'evil', type: 'minion',
    ability: 'Si el Demonio muere ejecutado (terminando la partida), se juega 1 día más. Si se ejecuta a un jugador, su equipo pierde.', firstNight: false, otherNights: false },
  // Demons
  ZOMBUUL: { id: 'ZOMBUUL', name: 'Zombuul', alignment: 'evil', type: 'demon',
    ability: 'Cada noche*: si nadie murió de día, elige un jugador: muere. La 1ª vez que mueras, sigues vivo pero pareces muerto.', firstNight: false, otherNights: true },
  PUKKA: { id: 'PUKKA', name: 'Pukka', alignment: 'evil', type: 'demon',
    ability: 'Cada noche: elige un jugador: se envenena. El jugador envenenado la noche anterior muere.', firstNight: true, otherNights: true },
  SHABALOTH: { id: 'SHABALOTH', name: 'Shabaloth', alignment: 'evil', type: 'demon',
    ability: 'Cada noche*: elige 2 jugadores: mueren. Un jugador muerto que elegiste anoche puede revivir.', firstNight: false, otherNights: true },
  PO: { id: 'PO', name: 'Po', alignment: 'evil', type: 'demon',
    ability: 'Cada noche*: puedes elegir un jugador: muere. Si anoche no elegiste a nadie, esta noche elige 3 jugadores.', firstNight: false, otherNights: true },
};

module.exports = {
  id: 'BAD_MOON_RISING',
  name: 'Bad Moon Rising',
  roles,
  distribution: tb.distribution,
  outsiderModifiers: {},
  queueFirst: [],
  queueOther: [],
};
