// ── Viajeros (suplemento de campañas) ─────────────────────────────
const roles = {
  APPRENTICE: { id: 'APPRENTICE', name: 'Aprendiz', alignment: 'good', type: 'traveler',
    ability: 'En tu primera noche ganas la habilidad de 1 Aldeano (si eres bueno) o 1 Esbirro (si eres malo).',
    firstNight: true, otherNights: false },
  BARISTA: { id: 'BARISTA', name: 'Barista', alignment: 'good', type: 'traveler',
    ability: 'Cada noche, hasta el crepúsculo, 1) un jugador está sobrio, sano y recibe información verdadera, o 2) su habilidad funciona 2 veces. El jugador sabe cuál de las dos.',
    firstNight: true, otherNights: true },
  BONE_COLLECTOR: { id: 'BONE_COLLECTOR', name: 'Coleccionista de Huesos', alignment: 'good', type: 'traveler',
    ability: 'Una vez por partida, por la noche, elige 1 jugador muerto: vuelve a ganar su habilidad hasta el crepúsculo.',
    firstNight: false, otherNights: true },
  BISHOP: { id: 'BISHOP', name: 'Obispo', alignment: 'good', type: 'traveler',
    ability: 'Sólo puede nominar el Narrador. Debe nominar al menos a 1 jugador del alineamiento contrario al Obispo cada día.',
    firstNight: false, otherNights: false },
  BUTCHER: { id: 'BUTCHER', name: 'Carnicero', alignment: 'good', type: 'traveler',
    ability: 'Cada día, después de la primera ejecución, puedes nominar otra vez.',
    firstNight: false, otherNights: false },
  DEVIANT: { id: 'DEVIANT', name: 'Pervertido', alignment: 'good', type: 'traveler',
    ability: 'Si has sido gracioso hoy no puedes ser exiliado.',
    firstNight: false, otherNights: false },
  HARLOT: { id: 'HARLOT', name: 'Meretriz', alignment: 'good', type: 'traveler',
    ability: 'Cada noche* elige 1 jugador vivo: si accede, descubres su personaje, pero ambos podéis morir.',
    firstNight: false, otherNights: true },
  JUDGE: { id: 'JUDGE', name: 'Juez', alignment: 'good', type: 'traveler',
    ability: 'Una vez por partida, si otro jugador ha nominado, puedes forzar la ejecución o impedirla.',
    firstNight: false, otherNights: false },
  MATRON: { id: 'MATRON', name: 'Institutriz', alignment: 'good', type: 'traveler',
    ability: 'Cada día puedes elegir hasta 3 parejas de jugadores para que cambien sus asientos. Los jugadores no pueden levantarse para hablar en privado.',
    firstNight: false, otherNights: false },
  VOUDON: { id: 'VOUDON', name: 'Voudon', alignment: 'good', type: 'traveler',
    ability: 'Solo tú y los muertos podéis votar. No necesitan ficha de votación para hacerlo. No es necesaria una mayoría para ejecutar.',
    firstNight: false, otherNights: false },
};

module.exports = { roles };
