// ── Viajeros (suplemento de campañas) ─────────────────────────────
const roles = {
  APPRENTICE: { id: 'APPRENTICE', name: 'Aprendiz', alignment: 'good', type: 'traveler',
    ability: 'Primera noche: ganas la habilidad de 1 Aldeano (si eres bueno) o 1 Esbirro (si eres malo).',
    firstNight: true, otherNights: false },
  BARISTA: { id: 'BARISTA', name: 'Barista', alignment: 'good', type: 'traveler',
    ability: 'Cada noche: elige un jugador. O actúa dos veces esta noche, o está sobrio y sano hasta el crepúsculo.',
    firstNight: true, otherNights: true },
  BONE_COLLECTOR: { id: 'BONE_COLLECTOR', name: 'Coleccionista de Huesos', alignment: 'good', type: 'traveler',
    ability: 'Una vez por partida, de noche: elige 1 jugador muerto → recupera su habilidad hasta el crepúsculo.',
    firstNight: false, otherNights: true },
  BISHOP: { id: 'BISHOP', name: 'Obispo', alignment: 'good', type: 'traveler',
    ability: 'Solo el Narrador nomina hoy. Debe nominar ≥1 del bando contrario al Obispo.',
    firstNight: false, otherNights: false },
  BUTCHER: { id: 'BUTCHER', name: 'Carnicero', alignment: 'good', type: 'traveler',
    ability: 'Tras la primera ejecución del día, el Carnicero puede nominar 1 jugador adicional.',
    firstNight: false, otherNights: false },
  DEVIANT: { id: 'DEVIANT', name: 'Desviado', alignment: 'good', type: 'traveler',
    ability: 'Si alguien intenta exiliarte sin causa justa, ese intento de exilio no cuenta.',
    firstNight: false, otherNights: false },
  HARLOT: { id: 'HARLOT', name: 'Meretriz', alignment: 'good', type: 'traveler',
    ability: 'Cada noche: elige un jugador. Si decide mostrarse, aprendes su personaje. El Narrador puede mataros a ambos.',
    firstNight: false, otherNights: true },
  JUDGE: { id: 'JUDGE', name: 'Juez', alignment: 'good', type: 'traveler',
    ability: 'Una vez por partida: puedes forzar una ejecución adicional o cancelar la ejecución actual.',
    firstNight: false, otherNights: false },
  MATRON: { id: 'MATRON', name: 'Institutriz', alignment: 'good', type: 'traveler',
    ability: 'Cada día puedes elegir hasta 3 parejas de jugadores para que intercambien sus asientos. No se pueden levantar.',
    firstNight: false, otherNights: false },
  VOUDON: { id: 'VOUDON', name: 'Voudon', alignment: 'good', type: 'traveler',
    ability: 'Mientras vivas: solo los muertos y el Voudon pueden votar. No se necesita mayoría para ejecutar.',
    firstNight: false, otherNights: false },
};

module.exports = { roles };
